name: test
on:
  workflow_dispatch: #github页面手动触发
  workflow_call: #允许其他workflow调用

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v4

      # - name: save-data
      #   run: sudo mysql -uroot -h 127.0.0.1 < dao/db.sql

      - name: add-configFile
        run: sudo cp config.example.yaml config.yaml

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - run: go version

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...
